name: json_mapper
version: 0.1.0
author: Ajithan Ravindiran <ajravindiran@gmail.com>
description: Simple lightweight JSON mapping utility.
homepage: http://theaj.net/
documentation: http://theaj.net/
