name: json_mapper
version: 0.1.0
author: Ajithan Ravindiran <ajravindiran@gmail.com>
description: Simple lightweight JSON mapping utility.
homepage: https://github.com/TheAJ/json_mapper
documentation: https://github.com/TheAJ/json_mapper
dependencies:
  unittest: '>=0.11.0 <0.12.0'
